# Generated by Django 5.2.11 on 2026-03-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLeafImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(choices=[('camera', 'Camera'), ('upload', 'Upload')], default='upload', max_length=24)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('image_type', models.CharField(blank=True, default='unknown', max_length=40)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('image_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
